클레임에 이메일, 이름, 유저명 추가
bacchus-snu/id pull request #236
Opened 2023-08-13 10:09 UTC by whnbaek

높은 확률로 안됨

2023-08-13 13:29 UTC, nevivurn requested changes
가능하면 테스트가 있었으면 좋겠지만 oidc 테스트하기 어려우니 어쩔 수 없군요
dev에 나중에 올려보고 이상한 데이터 추가해서 테스트해볼 수 있을 것 같습니다
scope 설정은 로컬에서 태스트 가능한데 해보신건가요?

2023-08-13 13:29 UTC, nevivurn commented on src/oidc/configuration.ts
> +        }
email 은 local만 들어가는것 같은데 의도된것같지 않습니다

2023-08-13 16:29 UTC, whnbaek commented
@nevivurn 테스트 안해봤습니다. dev에 올려서 직접 테스트하겠다는 의지이지요.

2023-08-14 08:53 UTC, tirr-c commented on src/oidc/configuration.ts
> +        }
```typescript
const primarySid = sidResult
  .map(sid => ({
    sid,
    year: Number(sid.length === 9 ? `19${sid.substring(0, 2)}` : sid.substring(0, 4)),
  }))
  .sort((a, b) => b.year - a.year)
  .map(({ sid }) => sid)[0];
```

2023-08-14 08:53 UTC, tirr-c commented on src/oidc/configuration.ts
> +        }
```suggestion
        if (sidResult.length === 0) {
          throw new Error('no student id');
        }
```

2023-08-14 08:53 UTC, tirr-c commented on src/oidc/configuration.ts
> +        }
```typescript
const { local: emailLocal, domain: emailDomain } =
  emailResult.find(({ domain }) => domain === 'snu.ac.kr')
  ?? emailResult[emailResult.length - 1];
const email = `${emailLocal}@${emailDomain}`;
```

2023-08-14 09:13 UTC, tirr-c requested changes

2023-08-14 09:13 UTC, tirr-c commented on src/oidc/configuration.ts
> +          student_id: sidResult[0],
```suggestion
          student_id: primarySid,
```

`primarySid` 안 쓴다고 밑줄 쳐주지 않나요

2023-08-14 09:14 UTC, whnbaek commented on src/oidc/configuration.ts
> +          student_id: sidResult[0],
쳐주는데 못봄

2023-08-14 09:18 UTC, tirr-c approved these changes

2023-08-19 14:19 UTC, nevivurn approved these changes

2023-08-19 14:20 UTC, merged